#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# autoenv
source /usr/local/opt/autoenv/activate.sh

# We do not need to load pyenv and rbenv if we are enabling the ruby/python
# modules

# pyenv
#eval "$(pyenv init -)"

# pyenv virtualenv
#eval "$(pyenv virtualenv-init -)"

# pyenv virtualenv wrapper
# export WORKON_HOME=$HOME/.virtualenvs
# export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"

# rbenv
# eval "$(rbenv init -)"

# colors
# export LSCOLORS="exfxcxdxbxegedabagacad"

# Android Development Environment 
export ANT_HOME=/usr/local/opt/ant
export MAVEN_HOME=/usr/local/opt/maven
export GRADLE_HOME=/usr/local/opt/gradle
export ANDROID_HOME=/usr/local/opt/android-sdk
export ANDROID_NDK_HOME=/usr/local/opt/android-ndk


# paths
path=(
  $ANT_HOME/bin
  $MAVEN_HOME/bin
  $GRADLE_HOME/bin
  $ANDROID_HOME/tools
  $ANDROID_HOME/platform-tools
  $ANDROID_HOME/build-tools/19.1.0
  $path
)
