#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...


# autoenv
source /usr/local/opt/autoenv/activate.sh

# We do not need to load pyenv and rbenv if we are enabling the ruby/python
# modules

# pyenv
#eval "$(pyenv init -)"

# pyenv virtualenv
#eval "$(pyenv virtualenv-init -)"

# pyenv virtualenv wrapper
# export WORKON_HOME=$HOME/.virtualenvs
# export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"

# rbenv
# eval "$(rbenv init -)"

# colors
# export LSCOLORS="exfxcxdxbxegedabagacad"

# paths
path=(
  /Applications/Postgres.app/Contents/Versions/9.4/bin
  $path
)
